version: '3.8'
services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ultimate_task
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - target: 5432
        published: 5433
    container_name: PostgreSQL
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 80
        published: 8080
    container_name: PHP_8.2
    environment:
      AUTH_TYPE: jwt
      DATABASE_URL: postgresql://postgres:postgres@PostgreSQL:5432/ultimate_task?serverVersion=15&charset=utf8
    depends_on:
      database:
        condition: service_healthy
