version: '3.8'

services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ultimate_task
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - target: 5432
        published: 5433

